# Generated by Django 4.2.3 on 2023-08-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_questions_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='created_on',
        ),
    ]
